name: work-flow

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

# permissions:
#     #id-token: write
#     contents: read

defaults:
    run:
        working-directory: ./enviornments/dev

jobs:
    workflow-practice:
        runs-on: ubuntu-latest
        # env:
        #     ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        #     ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
        #     ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            #ARM_USES_OIDC: true
        
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            
            - name: Azure Login
              uses: azure/login@v3
              with:
                client-id: "565d9381-0741-4b66-8786-f0d235b16260"
                tenant-id: "9f586574-489a-4616-9a09-be6ef4a540ea"
                subscription-id: "1145330a-eefd-43dc-89ce-992700e4cc8e"
                client-secret: ".JZ8Q~Nyn3V2b3YDELqBMF6IxAqPULczF3Xpvb9D"

            - name: Terraform setup
              uses: hashicorp/setup-terraform@v2

            - name: Terraform init
              run: terraform init

            - name: terraform validate
              run: terraform validate

            - name: terraform plan
              run: terraform plan
