name: work-flow

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

permissions:
    #id-token: write
    contents: read

defaults:
    run:
        working-directory: ./enviornments/dev

jobs:
    workflow-practice:
        runs-on: ubuntu-latest
        env:
            ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
            ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID}}
            ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            #ARM_USES_OIDC: true
        
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            
            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ env.ARM_CLIENT_ID}}
                tenant-id: ${{ env.ARM_TENANT_ID}}
                subscription-id: ${{ env.ARM_SUBSCRIPTION_ID}}
                client-secret: ${{ env.ARM_CLIENT_SECRET }}

            - name: Terraform setup
              uses: hashicorp/setup-terraform@v2

            - name: Terraform init
              run: terraform init

            - name: terraform validate
              run: terraform validate

            - name: terraform plan
              run: terraform plan
